Update gen.yml

diff --git a/.github/workflows/gen.yml b/.github/workflows/gen.yml
--- a/.github/workflows/gen.yml
+++ b/.github/workflows/gen.yml
@@ -15,20 +15,26 @@ jobs:
 
       - name: Install curl
         run: |
-          if not exist "curl-install" mkdir curl-install
-          cd curl-install
-          
+          set CURL_DIR=%GITHUB_WORKSPACE%\curl-install
+          if not exist "%CURL_DIR%" mkdir "%CURL_DIR%"
+          cd "%CURL_DIR%"
+
           powershell -Command "Invoke-WebRequest -Uri 'https://curl.se/windows/dl-8.4.0_7/curl-8.4.0_7-win64-mingw.zip' -OutFile 'curl.zip'"
           powershell -Command "Expand-Archive -Path 'curl.zip' -DestinationPath ."
 
-          for /d %%D in (curl-*-win64-mingw) do set "CURL_DIR=%%D"
-          move "!CURL_DIR!\bin\curl.exe" "%GITHUB_WORKSPACE%"
-          
-          cd %GITHUB_WORKSPACE%
-          rmdir /s /q curl-install
+          for /d %%D in (curl-*-win64-mingw) do set CURL_FOLDER=%%D
+          if exist "%CURL_FOLDER%\bin\curl.exe" (
+            copy "%CURL_FOLDER%\bin\curl.exe" "%GITHUB_WORKSPACE%"
+          ) else (
+            echo "Error: curl.exe not found in extracted folder" >&2
+            exit /b 1
+          )
 
-          echo %GITHUB_WORKSPACE%>> %GITHUB_PATH%
+          cd "%GITHUB_WORKSPACE%"
+          rmdir /s /q "%CURL_DIR%"
+          echo "%GITHUB_WORKSPACE%" >> "%GITHUB_PATH%"
         shell: cmd
+
 
       - name: Generate java_files.txt
         run: batch_files\generateFileStructure.bat
